Common code review
Jyotsna-Shetty/VehicleInfoCheck pull request #8
Opened 2021-06-17 08:02 UTC by Jyotsna-Shetty

2021-06-17 08:07 UTC, Jyotsna-Shetty commented
Android Studio arranges all the imports in alphabetical order. Even after manually changing it, the previous order is restored. Hence in some files the order of imports is the same as before.

2021-06-23 13:43 UTC, Dcruise546 requested changes
Overall, the code is okay.
I felt the comments were a bit too much! But it's my personal opinion.

General questions:
Why there are multiple instances of 'png' files?

After making the requested changes, please directly merge them without requesting another review!

2021-06-23 13:43 UTC, Dcruise546 commented on app/src/main/java/com/example/vehicleinfocheck/Element.java
> +// However, this class is not used in this project as the required methods did not work
Move this comment to first line of this file indicating this file is not part of this project!

2021-06-23 13:43 UTC, Dcruise546 commented on app/src/main/java/com/example/vehicleinfocheck/ImageActivity.java
> +    // onActivityResult method is used to display and save image as data of this app
either provide a blank space after a comment or don't. But follow this style throughout the project!

2021-06-23 13:43 UTC, Dcruise546 commented on app/src/main/java/com/example/vehicleinfocheck/ImageActivity.java
>                  Toast.makeText(this, "Camera Permission is Required to Use camera.", Toast.LENGTH_SHORT).show();
Why so many Caps?

2021-06-23 13:43 UTC, Dcruise546 commented on app/src/main/java/com/example/vehicleinfocheck/ImageActivity.java
> +                File f = new File(currentPhotoPath);  //creating file f from currentPhotoPath
f is not a good variable name

2021-06-23 13:43 UTC, Dcruise546 commented on app/src/main/java/com/example/vehicleinfocheck/ImageActivity.java
>              } catch (IOException ex) {
Do not keep unhandled exception! Always throw an error message or handle the exception (if there is any other possibility to solve the exception)

2021-06-23 13:43 UTC, Dcruise546 commented on app/src/main/java/com/example/vehicleinfocheck/WebActivity.java
> +            if (!vehicleNumber.getText().toString().trim().equals("")) {                        // Clip is made only if there is text to copy
Shouldn't there be a condition to check if the text is empty and throw an error message?

2021-06-26 14:24 UTC, merged